alias ttc='cd $HOME/.config/'
alias ttcf='cd $HOME/.config/fish/'
alias ttcn='cd $HOME/.config/neofetch/'
alias ttcr='cd $HOME/.config/rofi/'
alias ttct='cd $HOME/.config/tmux/'
alias ttr='cd $HOME/rice/'
